# Form implementation generated from reading ui file 'UI/menu.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Alert_tableView = QtWidgets.QTableView(parent=self.centralwidget)
        self.Alert_tableView.setGeometry(QtCore.QRect(30, 40, 256, 431))
        self.Alert_tableView.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.Alert_tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.Alert_tableView.setObjectName("Alert_tableView")
        self.Alert_timeEdit = QtWidgets.QTimeEdit(parent=self.centralwidget)
        self.Alert_timeEdit.setGeometry(QtCore.QRect(370, 190, 321, 29))
        self.Alert_timeEdit.setObjectName("Alert_timeEdit")
        self.Weekdays_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Weekdays_lineEdit.setGeometry(QtCore.QRect(370, 290, 321, 28))
        self.Weekdays_lineEdit.setObjectName("Weekdays_lineEdit")
        self.Diary_radioButton = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.Diary_radioButton.setGeometry(QtCore.QRect(370, 330, 111, 25))
        self.Diary_radioButton.setChecked(False)
        self.Diary_radioButton.setObjectName("Diary_radioButton")
        self.Days_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Days_label.setGeometry(QtCore.QRect(370, 240, 311, 41))
        self.Days_label.setWordWrap(True)
        self.Days_label.setObjectName("Days_label")
        self.Delete_pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Delete_pushButton.setGeometry(QtCore.QRect(30, 490, 251, 41))
        self.Delete_pushButton.setObjectName("Delete_pushButton")
        self.Create_pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Create_pushButton.setGeometry(QtCore.QRect(370, 380, 321, 51))
        self.Create_pushButton.setObjectName("Create_pushButton")
        self.Title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Title_label.setGeometry(QtCore.QRect(370, 40, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Title_label.setFont(font)
        self.Title_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.Title_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Title_label.setObjectName("Title_label")
        self.Name_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Name_lineEdit.setGeometry(QtCore.QRect(370, 120, 321, 28))
        self.Name_lineEdit.setObjectName("Name_lineEdit")
        self.Name_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Name_label.setGeometry(QtCore.QRect(370, 90, 321, 20))
        self.Name_label.setObjectName("Name_label")
        self.Time_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Time_label.setGeometry(QtCore.QRect(370, 170, 321, 20))
        self.Time_label.setObjectName("Time_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menuBar.setObjectName("menuBar")
        self.menuRemind_Me = QtWidgets.QMenu(parent=self.menuBar)
        self.menuRemind_Me.setObjectName("menuRemind_Me")
        MainWindow.setMenuBar(self.menuBar)
        self.menuBar.addAction(self.menuRemind_Me.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Diary_radioButton.setText(_translate("MainWindow", "Diary?"))
        self.Days_label.setText(_translate("MainWindow", "Write the days te alarm should be activated separated by commas ( ,)."))
        self.Delete_pushButton.setText(_translate("MainWindow", "Delete Alarm"))
        self.Create_pushButton.setText(_translate("MainWindow", "Create New Alarm"))
        self.Title_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:700;\">New Alarm</span></p></body></html>"))
        self.Name_label.setText(_translate("MainWindow", "Give your alarm a name"))
        self.Time_label.setText(_translate("MainWindow", "What time should the alarm go off?"))
        self.menuRemind_Me.setTitle(_translate("MainWindow", "Remind Me"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
